### ISSUE TITLE
Exported external package typings file cannot contain tripleslash references

### ISSUE THREAD

**Issue by luking4** [valor-software/ng2-handsontable#103]
Hi !
I have added grid according to instructions. But on building app, shows me multiple errors.(Mainly 3 errors)
1. Can't find index 
Error source: module.d.ts file on path -> ng2-handsontable\node_modules\ng2-bootstrap\dist
2. Build: Duplicate identifier 'require' and 'promise'
Error source: multiple files ts files like es6-object.d.ts, es6-promise.d.ts,index.d.ts etc.
3. Exported external package typings file cannot contain tripleslash references
Error source: index.ts on path -> ng2-handsontable\components
Below is my folder structure created.
Note: I have @angular2 installed folder while under ng2-handsontable has angular2. Is that the root cause?
![angular2-ng2-issue](https://cloud.githubusercontent.com/assets/19908616/16007948/f18f1342-3192-11e6-9cfa-345b477a5c7f.JPG)

**Comment by luking4** [comment]
OK,
This is how I solved build errors.

**Error**: 1. Can't find index
Error source: module.d.ts file on path -> ng2-handsontable\node_modules\ng2-bootstrap\dist
Code with issue:
File: module.d.ts
declare module 'ng2-bootstrap' {
  export * from 'index';
}
Code with **Fix**:
File: module.d.ts
 export * from './index';
I did same with module.d.ts file on path -> ng2-handsontable\components

**Error**: 2. Build: Duplicate identifier 'require' and 'promise'
Error source: multiple files ts files like es6-object.d.ts, es6-promise.d.ts,index.d.ts etc.
Resolution: Remove all references of es6-object.d.ts from all the places. Since compiler target is set to ES5. So, es6-object.d.ts is no longer needed.

**Error**: 3. Exported external package typings file cannot contain tripleslash references
Error source: index.ts on path -> ng2-handsontable\components
Code with issue:
File: index.ts
///<reference path = ....
export * from './handsontable/handsontable';
Code with **Fix**: Remove line with reference - no longer needed
File: index.ts
export * from './handsontable/handsontable';

I solved all the build errors. But still I am not able to load index.ts file on my demo.html. It shows following runtime error:

![angular2-ng2-issue2](https://cloud.githubusercontent.com/assets/19908616/16070371/6b30e0e4-32f2-11e6-8e29-60c691b042a0.JPG)

I don't understand what prevents index.ts loading. Due to this I am not able to integrate grid properly.

**Comment by luking4** [comment]
Following are the posts which I refer to fix build errors.
[Error: 1. Can't find index](http://stackoverflow.com/questions/32446039/typescript-cannot-find-js-module-in-same-folder)
[Error: 2. Build: Duplicate identifier 'require' and 'promise'](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/5015)
[Error: 3. Exported external package typings file cannot contain tripleslash references](https://github.com/urish/angular2-moment/commit/41d8eaa4e565333f7302402818331795f40a870f)

**Comment by EthanMia** [comment]
I am also having same issue. Did you find any solution for this problem?

**Comment by luking4** [comment]
@EthanMia , We tried a lot but couldn't integrate component. So, finally we had to choose another UI components which look to be more advanced. PrimeNG and Wijmo are two choices.
