### ISSUE TITLE
angular 2.0.0-beta.12

### ISSUE THREAD

**Issue by ericman93** [valor-software/ng2-handsontable#146]
I'm using angular2 version 2.0.0-beta.12
In this version the module _'angular2/angular2'_ is not exists, and handsontabe.ts is trying to get stuff from that module and fail

`import {OnInit, OnDestroy, Directive, EventEmitter, ElementRef} from 'angular2/angular2';`
should change to
`import {OnInit, OnDestroy, Directive, EventEmitter, ElementRef} from 'angular2/core;`

**Comment by renehamburger** [comment]
Everything should be working with angular@2.4.x now.
