### ISSUE TITLE
Update npm release?

### ISSUE THREAD

**Issue by PhilippSoehnlein** [valor-software/ng2-handsontable#162]
Hi,

can you publish the current version to npm, please?

I tried installing ng2-handsontable directly from GitHub but can't make it work in our angular-cli based application (mostly because the transpiled javascript files are missing when installing directly from GitHub). So I think an updated release would help a lot.

**Comment by valorkin** [comment]
not really, we stuck with handsontable dependencies so it is not working properly :(

**Comment by renehamburger** [comment]
NPM version is up-to-date now and works with angular@2.4.x.
