### ISSUE TITLE
angular 2 release

### ISSUE THREAD

**Issue by kkarandikar0807** [valor-software/ng2-handsontable#176]
hey guys, can you let us know till when can we expect the update for the angular 2 final release version?

**Comment by renehamburger** [comment]
See #231.

**Comment by renehamburger** [comment]
@valorkin, when are you planning to upgrade to Angular@2.x?

**Comment by valorkin** [comment]
Starting from v.19 had broken Umd imports, need to recheck, is it fixed

**Comment by renehamburger** [comment]
@valorkin, any update on this? Is there anything I could do to help?

**Comment by ryeyuen** [comment]
@valorkin. Great project! Any timeline for releasing the Angular 2.0 version?

**Comment by valorkin** [comment]
I wrote a tool to make publishing more easy, so I will be able to release soon

**Comment by ryeyuen** [comment]
Sounds good, look forward to seeing it!

**Comment by syriuszp** [comment]
@valorkin, when are you planning to upgrade to Angular@2.x?

**Comment by Rarely** [comment]
Interesting in trying this out with Angular 2.0 version. Excited for when its in.

**Comment by renehamburger** [comment]
We've update the package completely and it works well with angular@2.4.x now.
