### ISSUE TITLE
ng2-handsontable usage example

### ISSUE THREAD

**Issue by 093lus** [valor-software/ng2-handsontable#219]
I am new to angular2. And can someone drop a hint how to use the ng2-handsontable in my component. Maybe I have not included something.

**Comment by renehamburger** [comment]
ng2-handsontable isn't yet compatible with Angular2 release version, but see #231 including the updated demo.

**Comment by renehamburger** [comment]
We've update the package completely and it works well with `angular@2.4.x` now.
