### ISSUE TITLE
Is this working with beta versions of angular?

### ISSUE THREAD

**Issue by Thaenor** [valor-software/ng2-handsontable#24]
I'm using angular2 2.0.0-beta.0 either I'm missing something or I'm really not seeing how to include the new libraries into the components.ts

**Comment by valorkin** [comment]
no, it is doesn't right now

**Comment by Thaenor** [comment]
Thanks for letting me know. I'm trying ag-grid now. Still too early to make any comments on it.

**Comment by valorkin** [comment]
you can try ng2-table

**Comment by Thaenor** [comment]
Does it allow the cells to be editable? I'm currently struggling with ag-grid as it's not giving out any errors and yet the data isn't loading.
