### ISSUE TITLE
Angular 2 

### ISSUE THREAD

**Issue by sebastiendecraene** [valor-software/ng2-handsontable#275]
Is ng2-handsontable working on angular 2??

**Comment by renehamburger** [comment]
See #176 and #231. The PR has not been merged yet.

**Comment by ndefeijter** [comment]
Will it still be relevant since HandsOnTable plans to release its own Angular2 bindings?
https://trello.com/c/k0jNZPHv/25-new-wrapper-angular-2

**Comment by renehamburger** [comment]
Good spot, @ndefeijter. I'll check with the Handson team.

I've just update the code base to Angular 2.4. NPM module will be released shortly.

**Comment by ndefeijter** [comment]
Thanks, I'll check it out once available in NPM :-)

**Comment by RbkGh** [comment]
Is it ready for integration with angular 2 yet?

**Comment by renehamburger** [comment]
Yes, it is. We're running it with angular@2.4.x.

**Comment by RbkGh** [comment]
Good news.
