### ISSUE TITLE
Final NPM release

### ISSUE THREAD

**Issue by kkarandikar0807** [valor-software/ng2-handsontable#339]
Hey guys, I am seeing a lot of activity from the past few days. Thank you so much for updating this to angular 2.4. Is it on npm yet? Can I start using this in my project?

**Comment by ralberts** [comment]
@kkarandikar0807 

I noticed the latest version just got uploaded to npm - though I seem to be having trouble pulling it in via systemjs.  I am currently using ng2-handsontable-js until I can figure it out.  I am integrating ng2-handsontable with an [angular-seed project](https://github.com/mgechev/angular-seed) and running into:

`Uncaught (in promise): Error: Handsontable is not defined`

Even though handsontable.ts is loaded.
Anyway, would be good to know if someone else gets the same error or not :-).

**Comment by renehamburger** [comment]
@ralberts: would you be able to share your repository so I can reproduce the issue? Which version of Handsontable is installed: `npm list handsontable`?

**Comment by ralberts** [comment]
@renehamburger Thank you!  I was just going to sit down and take a look at it again :-).  Really appreciate your work on supporting this project!
