### ISSUE TITLE
Is there a import and export excel feature ?

### ISSUE THREAD

**Issue by hong-duc** [valor-software/ng2-handsontable#363]

**Comment by renehamburger** [comment]
The pro version of Handsontable allows [exporting to csv](https://docs.handsontable.com/pro/1.10.1/demo-export-file.html), but this wrapper only supports the free version out of the box. But you could always use a different module to import/export to Excel and use ng2-handsontable to display the data.

**Comment by varanmahesh** [comment]
https://github.com/varanmahesh/HandsonTableImport.git . Here i have built an import function for handsontable
