### ISSUE TITLE
Unable to load transpiler to transpile

### ISSUE THREAD

**Issue by hermansonl** [valor-software/ng2-handsontable#365]
When importing ng2-handsontable into the module file I get this error "Unable to load transpiler to transpile http://localhost:52607/node_modules/ng2-handsontable/index.js".

```javscript
"(SystemJS) XHR error (404 Not Found) loading http://localhost:52607/traceur/traceur.js
	Error: XHR error (404 Not Found) loading http://localhost:52607/traceur/traceur.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:52607/node_modules/zone.js/dist/zone.js:1242:29) [<root>]
	    at Zone.runTask (http://localhost:52607/node_modules/zone.js/dist/zone.js:166:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:52607/node_modules/zone.js/dist/zone.js:420:38) [<root>]
	Error loading http://localhost:52607/traceur/traceur.js
	Unable to load transpiler to transpile http://localhost:52607/node_modules/ng2-handsontable/index.js
	Error loading http://localhost:52607/node_modules/ng2-handsontable/index.js as "ng2-handsontable" from http://localhost:52607/app/app.module.js"
```

I used the quickstart files for Angular 2 to make sure it wasn't our own app that was conflicting with anything. Then npm install ng2-handsontable.

All I'm doing up to this point is adding the import to the module file.

```javascript
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent }  from './app.component';
import {HotTableModule} from 'ng2-handsontable';

@NgModule({
  imports:      [ BrowserModule, HotTableModule ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
```
I did try configuring traceur in another test to resolve the transpile error but it would lead to more errors in handsontable about $defineProperty is not a function.

```javascript
Error: (SystemJS) $defineProperty is not a function
	TypeError: $defineProperty is not a function
	    at Object.createClass (http://localhost:52607/node_modules/handsontable/dist/handsontable.full.js:22329:5)
```

**Comment by renehamburger** [comment]
Which quick start files did you use? Does it use Webpack or SystemJS for bundling?
ng2-handsontable should work with [Angular-CLI](https://github.com/angular/angular-cli) or the official [Angular2 seed](https://github.com/angular/angular2-seed) and TypeScript out-of-the-box. I haven't tested it with Traceur yet.

**Comment by hermansonl** [comment]
Thanks for the reply. I'm using this seed: https://github.com/angular/quickstart linked from the documentation. It's using SystemJS. 

I added 'ng2-handsontable': 'npm:ng2-handsontable/index.js' to the system config files as well as the import to the module file.

I'll test out the one you linked. If commonjs works instead of systemjs, I don't think it'll matter for our project to switch.

**Comment by hermansonl** [comment]
@renehamburger I used the Angular 2 seed you linked and was able to use ng2-handsontable. The styling didn't work but I can deal with that. Not sure if the issue is with using SystemJS or TypeScript compiling. Our projects are within Visual Studio so if webpack works then I'll look into converting our projects.

**Comment by renehamburger** [comment]
You will need to include Handsontable's css manually for now from `node_modules/handsontable/dist/handsontable.css`, e.g. as one of your component's styleUrls. I'll consider including that in ng2-handsontable straight away.

**Comment by renehamburger** [comment]
I was able to include ng2-handsontable with the current version of angular/quickstart (which does not include traceur). The one additional thing that is necessary with SystemJS which is to include `'ng2-handsontable': 'node_modules/ng2-handsontable/bundles/ng2-handsontable.umd.js'` in the systemjs.config.js.

**Comment by hermansonl** [comment]
@renehamburger That works wonders. Thanks for the help!
