### ISSUE TITLE
Custom Cell Renderer and Cell Editor

### ISSUE THREAD

**Issue by raskolnikov1041** [valor-software/ng2-handsontable#373]
Are there any samples or documentation in using custom renderers and editors?  I'm thinking it would be something like creating a component and assigning that component in the column definition as either the renderer or the editor. 

Thanks, team!

**Comment by renehamburger** [comment]
Here's a code snippets for using a custom cell renderer:

```ts
export class TableComponent {
  protected columnData: any[];
  protected handstontableOptions: ht.GridOptions;

  ...

  constructor() {
    const columns: ht.ColumnsOptions[] = this.columnData.map((col, index) => ({
      data: col.data,
      renderer: (instance: any, td: Element, row: number, col: number, columnKey: string, data: any, cellProperties: any) => {
        if (data.html) {
          $(td).html(data.html);
        } else {
          Handsontable.renderers.TextRenderer.apply(instance, arguments);
        }
      }
    }));
    this.handstontableOptions.columns = columns;
  }
}
```

with 

```html
<hot-table [options]="handstontableOptions">
</hot-table>

```

Does that help?

**Comment by raskolnikov1041** [comment]
Thanks, Rene.

Yup, that's for custom cell renderer. But actually I'm more interested in custom cell editors.  I believe HOT supports this.

https://docs.handsontable.com/0.15.0-beta1/tutorial-cell-editor.html

**Comment by renehamburger** [comment]
I haven't tried that yet, but it should work analogously. Feel free to share some example code if you get it to work.

**Comment by ben-dalton** [comment]
@raskolnikov1041 Were you able to implement a custom editor? I'd love to see an example of this.

**Comment by raskolnikov1041** [comment]
@ben-dalton Unfortunately, i didnt pursue the use of HOT.

**Comment by Zenoware** [comment]
Has anyone gotten this to work?  This is a pretty big show stopper for this, otherwise, this component works fairly well (minus weird rendering of cells to headers)

**Comment by ben-dalton** [comment]
I was able to add a custom editor relying heavily on [this documentation](https://docs.handsontable.com/pro/1.12.0/tutorial-cell-editor.html). I needed a select box that takes key/value pairs instead of an array of strings. Here is the editor (I'm sure it could be cleaned up): https://gist.github.com/ben-dalton/6fd4cad0917cad150324afc8060562a3

Then I could import the editor and point to it in the columns array, e.g.
```
import { SelectValueEditor } from '../shared/utils/handsontable/editors';
...
const columns = [
  {  
    data: 'campusId', 
    strict: true,
    filter: false,
    renderer: SelectValueRenderer,
    editor: SelectValueEditor,
    selectOptions: () => this.campusList,
    required: true
  }
] 
```

**Comment by Zenoware** [comment]
@ben-dalton I actually copied your code but it still does not appear to work.  I've set breakpoints in the prepare function with no luck there either.  Any suggestions?

**Comment by ben-dalton** [comment]
@Zenoware my code is pretty tightly coupled to the structure of my containing component so I think it will only be helpful as a reference. My implementation depends on a campusList function on the class that pulls back some data. It might be better to try and implement a simpler editor or renderer, just to get your bearings and see some results to start with. The password editor in the docs was the most helpful for me.

**Comment by Zenoware** [comment]
@ben-dalton I did figure out the problem.  It was that I was setting the columns in an observable.  Not sure why that was a problem but it caused renderer and editor to not work at all.  Moving it out and just updating the optionsList works inside the observable.  Only issue now is that the rerender is not being fired after the change event.  It does change the value of the cell though
