### ISSUE TITLE
The event callback did not work with sample code

### ISSUE THREAD

**Issue by zhejingl** [valor-software/ng2-handsontable#375]
Hi,
      Thank you for providing this package. 
      I installed ng2-handsontable in my project. I copy/paste the sample demo program. The table displayed correctly, but the even call backs are not been invoked. I searched the internet and did not find any issue regrading this. So I think I might missed something...
      I will be very appreciate with your help!
Thanks,
Kenny[](url)

**Comment by fcc95** [comment]
hello @zhejingl @valorkin 
 I have same problem can u give me solution?
