### ISSUE TITLE
Not working with angular 4.0.0

### ISSUE THREAD

**Issue by jana4v** [valor-software/ng2-handsontable#385]
Below is error from firefox console
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
    [WARNING ->]<template [ngIf]="true">
        <col [class.k-group-col]="true" *ngFor="let g of groups" />
        "): ng:///SharedModule/ColGroupComponent.html@1:4  core.umd.js:3060:9
Environment config Object { API: "https://demo.com", ENV: "DEV" }  app.component.js:17:9
Angular is running in the development mode. Call enableProdMode() to enable the production mode.  core.umd.js:3052:9
ERROR Error: Uncaught (in promise): TypeError: registeredOverlays[type] is not a constructor
[12]</<.createOverlay@http://localhost:5555/node_modules/ng2-handsontable/bundles/ng2-handsontable.umd.js:7924:12
WalkontableOverlays@http://localhost:5555/static/handsontable/handsontable.full.js:2173:26
Walkontable@http://localhost:5555/static/handsontable/handsontable.full.js:1153:23
TableView@http://localhost:5555/static/handsontable/handsontable.full.js:20851:13
Core/this.init@http://localhost:5555/static/handsontable/handsontable.full.js:5096:17
Handsontable@http://localhost:5555/static/handsontable/handsontable.full.js:4232:3
HotTable.prototype.ngOnInit@http://localhost:5555/app/shared/handsontable/handsontable_WAMP.js:222:21
checkAndUpdateDirectiveInline@http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:10766:9
checkAndUpdateNodeInline@http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:12144:17
checkAndUpdateNode@http://localhost:5555/node_modules/@angular/core/b…
Stack trace:
[object Object]

**Comment by soares741** [comment]
were you able to solve this issue? I am having the same problem now

**Comment by elgame** [comment]
Hi, any solution to this problem?

**Comment by soares741** [comment]
I had this issue while I was trying to use the pro version. Once I moved to the free version the problem disappeared.

**Comment by renehamburger** [comment]
I've just done an upgrade to Angular4: [Release 1.0.0](https://github.com/valor-software/ng2-handsontable/releases/tag/1.0.0). Would you be able to check whether your issue has been resolved? It should be published to npm in the next few days.

**Comment by renehamburger** [comment]
I added another release, as AOT didn't work yet: [1.0.1](https://github.com/valor-software/ng2-handsontable/releases/tag/1.0.1). Please also note the [breaking changes](https://github.com/valor-software/ng2-handsontable/blob/master/CHANGELOG.md#101-2017-05-26) introduced in the 1.x release.

If you want to test this locally before it's available on npm, you can:
- clone ng2-handsontable and check out the master branch
- run `npm run build` in that directory
- add an ng2-handsontable entry to your project's package.json pointing to the dist folder you have just built, e.g. `"ng2-handsontable": "../ng2-handsontable/dist"`
