### ISSUE TITLE
Explain use of Core Methods in ng directive

### ISSUE THREAD

**Issue by nethore** [valor-software/ng2-handsontable#401]
Hi,

I'm trying to use CoreMethods like updateSettings() from Handsontable but I can't find anywhere in the doc or in the demo files where Core Methods are call with ng2-handsontable.

It might be a good idea to write a small explanation or the clearly write if they are not available.

Thanks in Advance.

**Comment by danielhansson** [comment]
@nethore did you find any solution to this?

**Comment by nethore** [comment]
No, I didn't find a way to use CoreMethods.
What I've done is that I call a function that returns an option object in [options] to get my updated settings.

**Comment by soares741** [comment]
I am having the same problem. I want to use the core methods and without these functionalities the library is useless to me

**Comment by renehamburger** [comment]
Apologies for the slow response.

I will add an instance getter some time soon, but for now you can get the the Handsontable instance from within any hook callback as its function context (provided it's not not an arrow function):
```ts
const options = {
  init: function () {
    const instance: ht.Instance = this;
  }
}
```

**Comment by nethore** [comment]
Any news about a better way to do it ?
