### ISSUE TITLE
Get instance inside afterChange()

### ISSUE THREAD

**Issue by danielhansson** [valor-software/ng2-handsontable#413]
I wan't to be able to do something similar to this:
http://jsfiddle.net/qcr2r6fp/

But how do I get hold of the instance inside of the afterChange method so I can use updateSettings?

**Comment by renehamburger** [comment]
All Handonstable hooks are called with the Handsontable instance as the function context, so you can call `updateSettings()` directly on `this` within the function (assuming it's not a arrow function).
