### ISSUE TITLE
Upgrade to Angular 4.X.X

### ISSUE THREAD

**Issue by lahloumehdi** [valor-software/ng2-handsontable#439]
Hello can you upgrade ng2-handsontable to ngX-handsotable ? 

+-- UNMET PEER DEPENDENCY @angular/common@4.1.3
+-- UNMET PEER DEPENDENCY @angular/compiler@4.1.3
+-- UNMET PEER DEPENDENCY @angular/core@4.1.3
+-- UNMET PEER DEPENDENCY @angular/forms@4.1.3
`-- ng2-handsontable@0.48.0
  `-- handsontable@0.31.2
    +-- moment@2.18.1
    +-- numbro@1.11.0
    +-- pikaday@1.5.1
    `-- zeroclipboard@2.3.0

**Comment by renehamburger** [comment]
I've just done an upgrade to Angular4: [Release 1.0.0](https://github.com/valor-software/ng2-handsontable/releases/tag/1.0.0). Would you be able to check whether your issue has been resolved? It should be published to npm in the next few days.

**Comment by renehamburger** [comment]
See #385.
