### ISSUE TITLE
After change event and after cell mouse down events are not working

### ISSUE THREAD

**Issue by kaustubhdeshpande** [valor-software/ng2-handsontable#463]
Hi, 
I integrated ng2 handsontable basic in my project.
now i want to fire event on click of cell. but it is not working at my end.
also i am not getting any error on the console.
thanks.

**Comment by renehamburger** [comment]
These sounds more like a support request. Please post it on https://stackoverflow.com under the tag `ng2-handsontable`. Make sure you include at least snippets of your code and the exact error message.
