### ISSUE TITLE
Get HotTable Instance to force render

### ISSUE THREAD

**Issue by vfsunny** [valor-software/ng2-handsontable#464]
Hi together,

I´m having problems with accessing the HotTable Instance in order to force a re-render for Data changes from JS (weirdly the table shows the changes when I scroll).
I tried to access it from a Parent Component with 
@ViewChild(HotTableComponent) hotTableComponent,
where HotTableComponent is the Components Class, which shows the HotTable. But hotTableComponent is always undefined. If I try to use @ViewChild(HotTable) hotTableComponent, I get an TS error that HotTable is undefined.

Is this a Bug or am I doing something wrong?

**Comment by renehamburger** [comment]
Which version of ng2-handstontable are you using? `@ViewChild(HotTable) hotTableComponent` should work, but will only be available after the OnInit lifecycle hook.

**Comment by vfsunny** [comment]
I´m using ng2-handsontable@1.0.1. The problem is, that the app doesnt render, but stops with the following error:
`Error: (SystemJS) HotTable is not defined
	ReferenceError: HotTable is not defined
	    at execute (https://127.0.0.1:9999/components/import/import.menu.component.ts!transpiled:28:34)`

The Parent component itself doenst to much atm:

`import {Component, OnInit, ViewChild} from '@angular/core';
@Component({
	selector: 'import-menu',
	templateUrl: 'views/import/import.menu.component.html',
	styles: ['.fullSize { width: 100%; height: 100% }']
})
export class ImportMenuComponent implements OnInit {
	@ViewChild(HotTable) private hotTableComponent;

	constructor() {

	}

	ngOnInit() {
		
	}

}
`

**Comment by renehamburger** [comment]
You will need to import HotTable, too: `import { HotTable } from 'ng2-handsontable';`.
