### ISSUE TITLE
language setting is not working

### ISSUE THREAD

**Issue by sanjarbek** [valor-software/ng2-handsontable#477]
> ERROR Error: Unknown culture : ru-RU
>    at Function.webpackJsonp.../../../../numbro/numbro.js.numbro.culture (http://localhost:4201/vendor.bundle.js:85882:23)

i am using "ng2-handsontable": "^1.0.3" version.
I tried install numbro separately, but in this case there are conflict on building process.

**Comment by laurent1024** [comment]
Try somthing like this your component:

```
import * as numbro from 'numbro';

@Component( {
    selector: 'mycomponent',
    templateUrl: './mycomponent.html'
})
export class MyComponent  {
    constructor( ) {
        numbro.loadCulturesInNode();
   }
}
```

**Comment by sanjarbek** [comment]
@laurent1024 it is working. Thank you!

**Comment by felps** [comment]
I would derive for a million years before figuring that out! Thank you very much @laurent1024 !
