### ISSUE TITLE
bundling

### ISSUE THREAD

**Issue by sebastiendecraene** [valor-software/ng2-handsontable#480]
Can you tell me how you bundle this project?

**Comment by renehamburger** [comment]
If you are using webpack (e.g. with Angular-CLI), it will be bundled automatically. Someone has reported [an issue](https://github.com/valor-software/ng2-handsontable/issues/475) with loading it in a lazily loaded module, so best to keep it in the main module for now. If you need more help,  please ask a question at [StackOverflow with the tags `angular` and `handsontable`](https://stackoverflow.com/questions/tagged/angular+handsontable).
