### ISSUE TITLE
How refresh data after server call?

### ISSUE THREAD

**Issue by cmh234** [valor-software/ng2-handsontable#481]
How do I refresh the data after a server call? in AngularJS I did something like this. All day I can't figure out how to get it to work.

MainCtrl.$inject = ['$http','hotRegisterer']

$http.get('../data/zips.json').success(function(data){ 
        hotRegisterer.getInstance('my-handsontable').loadData(data);
      }).error(function(msg,code){
        console.log(msg);
      });  

<hot-table
    hot-id="my-handsontable"
    settings="ctrl.settings"
    row-headers="ctrl.rowHeaders"
    col-headers="ctrl.colHeaders"
    datarows="ctrl.db.items"
    >
  </hot-table>

**Comment by renehamburger** [comment]
@cmh234, this is a module for Angular 2+. Are you trying to use it with Angular 1? If you are, try out https://github.com/handsontable/ngHandsontable instead.

**Comment by cmh234** [comment]
I'm using angular 2.   I can't get the spreadsheet to update after I've made an asynchronous call for the data.  The example I posted was how i used to do it.  Using angular 2  I want to update the spreadsheet after an asynchronous call how do I do that?
