### ISSUE TITLE
Cannot find module 'rxjs-compat/Observable' - Angular 6 app build issue

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [valor-software/ng2-handsontable#505]
i am trying to upgrade my angular5 app to angular6. When i compile angular6 app getting build error.  look like import statement need to be fixed. from "import { Observable } from 'rxjs/Observable'" to "import { Observable } from 'rxjs" in "handsontable.component.d.ts" file. i can see github source has correct import statement but "2.1.0-rc.3" latest version still has old files. please help

![image](https://user-images.githubusercontent.com/16232384/43147519-d674b580-8f28-11e8-8312-d17892fe4faa.png)

**Comment by duangrudee** [comment]
This solved the problem on my machine
```
npm install --save rxjs-compat
```

**Comment by anmol-rodi** [comment]
thanks @duangrudee  it worked for me

**Comment by anitta-paul** [comment]
Had the same issue. Worked for me too. Thanks

**Comment by darshansidar** [comment]
> This solved the problem on my machine
> 
> ```
> npm install --save rxjs-compat
> ```

This really solved the issues

**Comment by wandersonsc** [comment]
Yup, running npm install --save rxjs-compat did the trick.

**Comment by PrakashKumar-27** [comment]
wow! its working..

**Comment by jgonzal10** [comment]
thanks, it worked for me too!!!

**Comment by MarkRobles** [comment]
thank you!!!

**Comment by ghost** [comment]
compiler.js:1021 Uncaught Error: Unexpected value 'NgRedux' imported by the module 'AppModule'. Please add a @NgModule annotation.

**Comment by cevaho** [comment]
Thanks !

**Comment by developer504** [comment]
Thanks, it worked for me also!

**Comment by keilaeneas** [comment]
Thanks, it really helped me

**Comment by JohnSnow93** [comment]
thanks!

**Comment by fvanwijk** [comment]
Since Angular 7, `rxjs-compat` isn't in your project automatically. Also when you run the [Angular updater](update.angular.io):
![image](https://user-images.githubusercontent.com/963136/49011753-9059b300-f177-11e8-95de-eeea63483e80.png)

**Comment by epiphanizer** [comment]
<3 the answers above

**Comment by ravikumar-j** [comment]
thanks a lot its worked

**Comment by murali-veerla** [comment]
its working fine

**Comment by Prabhu1995** [comment]
its working fine

**Comment by BryanJec** [comment]
Thanks

**Comment by nickofthyme** [comment]
This issue is because you are still using `rxjs@v5` syntax that has been deprecated in `rxjs@v6`.

Installing `rxjs-compat` will supplement `rxjs@v6` with the missing/deprecated code as a fallback which is why it's complaining. You are still using the old syntax.

```ts
// old v5 syntax
import { Observable } from 'rxjs/Observable'
// new v6 syntax
import { Observable } from 'rxjs'
```

The real solution should be removing `rxjs@v5` syntax and refactoring your code to use only `rxjs@v6` in which case you will **_NOT_** need to include `rxjs-compat`. See this [guide](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md#dropping-the-compatibility-layer) for what code changes to make from 5 -> 6, they are mostly pretty easy.

**Comment by KishoreUtukuru** [comment]
Thanks! it worked for me

**Comment by sikemullivan** [comment]
@nickofthyme Thanks for the updated solution. 

Before:

```
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { environment } from '../../../environments/environment';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import { Observable } from 'rxjs/Rx';
import { ServiceException } from '../ServiceException';

@Injectable()
export class ActivityService {
    private _baseUrl = '/api/Activities';

    constructor(private http: HttpClient) { }

    get(): Observable<ActivitiesResponse> {
        return this.http.get<ActivitiesResponse>(
            environment.protocol + environment.baseApiUrl + this._baseUrl)
            .catch(error => {
                console.log(error);
                return Observable.throw(new ServiceException());
            });
    }
}
```

After:

```
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { environment } from '../../../environments/environment';
import { map, catchError } from 'rxjs/operators';
import { Observable } from 'rxjs';
import { ServiceException } from '../ServiceException';

@Injectable()
export class ActivityService {
    private _baseUrl = '/api/Activities';

    constructor(private http: HttpClient) { }

    get(): Observable<ActivitiesResponse> {
        return this.http.get<ActivitiesResponse>(
            environment.protocol + environment.baseApiUrl + this._baseUrl)
            .pipe(
                catchError(error => {
                    console.log(error);
                    return Observable.throw(new ServiceException());
                })
            );
    }
}
```

**Comment by yogeshpatil143** [comment]
npm i rxjs-compat

Please add these command on your root folder

**Comment by haja12** [comment]
Thanks a lot, it is working for me

**Comment by yogeshpatil143** [comment]
Please let me know if anything that i assist you.. @haja12

**Comment by OrlandoHC** [comment]
> This solved the problem on my machine
> 
> ```
> npm install --save rxjs-compat
> ```

It is working for me, thank you very much.

**Comment by yogeshpatil143** [comment]
npm i rxjs-compat

Please add these command on your root folder

**Comment by drissboumlik** [comment]
Thank you so much, it worked - npm install --save rxjs-compat

**Comment by priyankaselvam104** [comment]
thamk u ... helpful

**Comment by isotope3** [comment]
Your code is complaining beacause 'Observable' is no more in 'rxjs/Observable'. It has been moved to 'rxjs' itself. So instead of installing the compatibility module, if you update your imports to match what's present in ver 6+ of RxJs, your errors "should" go away.

**Comment by nagipogu** [comment]
" Cannot find module 'rxjs-compat/Observable': " solved the problem on my machine

npm install --save rxjs-compat

**Comment by vilchessili** [comment]
> This solved the problem on my machine
> 
> ```
> npm install --save rxjs-compat
> ```

Thanks a lot!! it's working

**Comment by SuiCxDe007** [comment]
@duangrudee works for ionic too!!!

**Comment by hyhypepe** [comment]
Thank you so much. It worked!

**Comment by RaviKiranM900** [comment]
Thanks a lot...it worked!

**Comment by yogeshpatil143** [comment]
> @duangrudee works for ionic too!!!

yes

**Comment by cluzier** [comment]
> This solved the problem on my machine
> 
> ```
> npm install --save rxjs-compat
> ```

thank you this helped.

**Comment by daniele-pecora** [comment]
> This solved the problem on my machine
> 
> ```
> npm install --save rxjs-compat
> ```

thx, this did it

**Comment by riginoommen** [comment]
> Since Angular 7, `rxjs-compat` isn't in your project automatically. Also when you run the [Angular updater](update.angular.io):
> ![image](https://user-images.githubusercontent.com/963136/49011753-9059b300-f177-11e8-95de-eeea63483e80.png)

Hi 

How to fix this while migrating from angular 5 to 7

**Comment by pavisbalu** [comment]
yay it worked :)

**Comment by rojasjandro89** [comment]
how is installing rxjs-compat the solution here? The idea is to get rid of it 🙄🤦‍♂️

All you need to do is correct your imports...  for example, import Observable from 'rxjs' directly instead of 'rxjs/Observable'... the same with subjects and behavior subjects etc...

**Comment by nickofthyme** [comment]
@rojasjandro89 Thank you! 🤣 

I think people are just scrambling to make it work and fail to see/address the actual issue!

They'll just have to fix it later.....

**Comment by yashsony** [comment]
yarn add rxjs-compat --save

**Comment by OlatunjiGab** [comment]
Npm install --save rxjs-compact did not work on my machine any help pls

**Comment by nickofthyme** [comment]
@OlatunjiGab what is your error log?

**Comment by OlatunjiGab** [comment]
It displays typescript error cannot find module rxjs/observable even after installing the plug-in above

**Comment by nickofthyme** [comment]
Ok soooo what is the error exactly, copy/paste it here 👇 

Also what version of rxjs are you using and which version did you migrate from?

**Comment by OlatunjiGab** [comment]
[app-scripts] [16:26:07]  typescript: ...s/GabFile/MyProject/FPImobile/node_modules/@angular/common/http/src/backend.d.ts, line: 8 
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L8:  * `HttpHandler` is injectable. When injected, the handler instance dispatches requests to the
[app-scripts]        L9:  * first interceptor in the chain, which dispatches to the second, etc, eventually reaching the
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L1:  import { Observable } from 'rxjs';
[app-scripts]        L2:  import { HttpHandler } from './backend';
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L9:  * Most interceptors will transform the outgoing request before passing it to the
[app-scripts]       L10:  * next interceptor in the chain, by calling `next.handle(transformedReq)`.
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L1:  import { Observable } from 'rxjs';
[app-scripts]        L2:  import { HttpBackend, HttpHandler } from './backend';
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L8:  * An `HttpHandler` that applies a bunch of `HttpInterceptor`s
[app-scripts]        L9:  * to a request before passing it to the given `HttpBackend`.
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L1:  import { Observable } from 'rxjs';
[app-scripts]        L2:  import { HttpBackend } from './backend';
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L1:  import { InjectionToken } from '@angular/core';
[app-scripts]        L2:  import { Observable } from 'rxjs';
[app-scripts]        L3:  import { HttpHandler } from './backend';
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L1:  import { ISubscription } from 'rxjs';
[app-scripts]        L2:  import { LocationStrategy } from './location_strategy';
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L8:  * The `async` pipe subscribes to an `Observable` or `Promise` and returns the latest value it has
[app-scripts]        L9:  * emitted. When a new value is emitted, the `async` pipe marks the component to be checked for
[app-scripts]       L10:  * changes. When the component gets destroyed, the `async` pipe unsubscribes automatically to avoid
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L7:  import { Type } from './type';
[app-scripts]        L8:  import { NgZone } from './zone/ng_zone';    
[app-scripts]        L9:  export declare const ALLOW_MULTIPLE_PLATFORMS: InjectionToken<boolean>;
[app-scripts]             Cannot find module 'rxjs/Subject'.
[app-scripts]        L7:  * In the following example, `Zippy` alternatively emits `open` and `close` events when its
[app-scripts]        L8:  * title gets clicked:              
[app-scripts] [16:26:07]  typescript: ...ts/GabFile/MyProject/FPImobile/node_modules/@angular/common/http/src/client.d.ts, line: 1 
[app-scripts] [16:26:07]  typescript: ...bFile/MyProject/FPImobile/node_modules/@angular/common/http/src/interceptor.d.ts, line: 9 
[app-scripts] [16:26:07]  typescript: ...nts/GabFile/MyProject/FPImobile/node_modules/@angular/common/http/src/jsonp.d.ts, line: 1 
[app-scripts] [16:26:07]  typescript: ...ts/GabFile/MyProject/FPImobile/node_modules/@angular/common/http/src/module.d.ts, line: 9 
[app-scripts] [16:26:07]  typescript: ...ments/GabFile/MyProject/FPImobile/node_modules/@angular/common/http/src/xhr.d.ts, line: 1 
[app-scripts] [16:26:07]  typescript: ...ents/GabFile/MyProject/FPImobile/node_modules/@angular/common/http/src/xsrf.d.ts, line: 2 
[app-scripts] [16:26:07]  typescript: ...File/MyProject/FPImobile/node_modules/@angular/common/src/location/location.d.ts, line: 1 
[app-scripts] [16:26:07]  typescript: ...bFile/MyProject/FPImobile/node_modules/@angular/common/src/pipes/async_pipe.d.ts, line: 9 
[app-scripts] [16:26:07]  typescript: .../GabFile/MyProject/FPImobile/node_modules/@angular/core/src/application_ref.d.ts, line: 8 
[app-scripts] [16:26:07]  typescript: ...ts/GabFile/MyProject/FPImobile/node_modules/@angular/core/src/event_emitter.d.ts, line: 8 
[app-scripts] [16:26:07]  typescript: ...abFile/MyProject/FPImobile/node_modules/@angular/core/src/linker/query_list.d.ts, line: 8 
[app-scripts] [16:26:07]  typescript: ...uments/GabFile/MyProject/FPImobile/node_modules/@angular/core/src/util/lang.d.ts, line: 8 
[app-scripts] [16:26:07]  typescript: ...obile/node_modules/@angular/forms/src/directives/abstract_control_directive.d.ts, line: 8 
[app-scripts] [16:26:07]  typescript: ...e/MyProject/FPImobile/node_modules/@angular/forms/src/directives/validators.d.ts, line: 9 
[app-scripts] [16:26:07]  typescript: ...Documents/GabFile/MyProject/FPImobile/node_modules/@angular/forms/src/model.d.ts, line: 1 
[app-scripts] [16:26:07]  typescript: ...ents/GabFile/MyProject/FPImobile/node_modules/@angular/forms/src/validators.d.ts, line: 9 
[app-scripts] [16:26:07]  typescript: ...e/MyProject/FPImobile/node_modules/@angular/http/src/backends/jsonp_backend.d.ts, line: 1 
[app-scripts] [16:26:07]  typescript: ...ile/MyProject/FPImobile/node_modules/@angular/http/src/backends/xhr_backend.d.ts, line: 1 
[app-scripts] [16:26:07]  typescript: ...l/Documents/GabFile/MyProject/FPImobile/node_modules/@angular/http/src/http.d.ts, line: 1 
[app-scripts] [16:26:07]  typescript: ...ents/GabFile/MyProject/FPImobile/node_modules/@ionic-native/core/decorators.d.ts, line: 1 
[app-scripts] [16:26:07]  typescript: ...ocuments/GabFile/MyProject/FPImobile/node_modules/@ionic-native/core/plugin.d.ts, line: 1 
[app-scripts] [16:26:07]  typescript: ...abFile/MyProject/FPImobile/node_modules/@ionic-native/geolocation/ngx/index.d.ts, line: 2 
[app-scripts] [16:26:07]  typescript: ...ocuments/GabFile/MyProject/FPImobile/node_modules/angularfire2/angularfire2.d.ts, line: 3 
[app-scripts] [16:26:07]  typescript: ...l/Documents/GabFile/MyProject/FPImobile/node_modules/angularfire2/auth/auth.d.ts, line: 3 
[app-scripts] [16:26:07]  typescript: .../MyProject/FPImobile/node_modules/angularfire2/firestore/collection/changes.d.ts, line: 3 
[app-scripts] [16:26:07]  typescript: ...Project/FPImobile/node_modules/angularfire2/firestore/collection/collection.d.ts, line: 3 
[app-scripts] [16:26:07]  typescript: ...e/MyProject/FPImobile/node_modules/angularfire2/firestore/document/document.d.ts, line: 3 
[app-scripts] [16:26:07]  typescript: ...s/GabFile/MyProject/FPImobile/node_modules/angularfire2/firestore/firestore.d.ts, line: 3 
[app-scripts] [16:26:07]  typescript: .../GabFile/MyProject/FPImobile/node_modules/angularfire2/firestore/interfaces.d.ts, line: 1 
[app-scripts] [16:26:07]  typescript: .../MyProject/FPImobile/node_modules/angularfire2/firestore/observable/fromRef.d.ts, line: 2 
[app-scripts] [16:26:07]  typescript: ...bFile/MyProject/FPImobile/node_modules/ionic-angular/components/input/input.d.ts, line: 3 
[app-scripts] [16:26:07]  typescript: ...GabFile/MyProject/FPImobile/node_modules/ionic-angular/components/tabs/tabs.d.ts, line: 2 
[app-scripts] [16:26:07]  typescript: C:/Users/Gabriel/Documents/GabFile/MyProject/FPImobile/src/app/app.module.ts, line: 9 
[app-scripts] [16:26:07]  typescript: C:/Users/Gabriel/Documents/GabFile/MyProject/FPImobile/src/pages/home/home.ts, line: 2 
[app-scripts] [16:26:07]  typescript: C:/Users/Gabriel/Documents/GabFile/MyProject/FPImobile/src/pages/home/home.ts, line: 12 
[app-scripts] [16:26:07]  typescript: ...ers/Gabriel/Documents/GabFile/MyProject/FPImobile/src/pages/playlist/playlist.ts, line: 2 
[app-scripts] [16:26:07]  typescript: ...ers/Gabriel/Documents/GabFile/MyProject/FPImobile/src/pages/playlist/playlist.ts, line: 18 
[app-scripts] [16:26:07]  typescript: ...s/Gabriel/Documents/GabFile/MyProject/FPImobile/src/pages/timetable/timetable.ts, line: 4 
[app-scripts] [16:26:07]  typescript: ...s/Gabriel/Documents/GabFile/MyProject/FPImobile/src/pages/timetable/timetable.ts, line: 17 
[app-scripts] [16:26:07]  typescript: ...:/Users/Gabriel/Documents/GabFile/MyProject/FPImobile/src/providers/chat/chat.ts, line: 4 
[app-scripts] (node:916) UnhandledPromiseRejectionWarning: Error: A watch configured to watch the following paths failed to start. It likely that a file referenced does not exist: C:\Users\Gabriel\Documents\GabFile\MyProject\FPImobile\src\**\*.(ts|html|s(c|a)ss)
[app-scripts]     at new BuildError (C:\Users\Gabriel\Documents\GabFile\MyProject\FPImobile\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
[app-scripts]     at Timeout._onTimeout (C:\Users\Gabriel\Documents\GabFile\MyProject\FPImobile\node_modules\@ionic\app-scripts\dist\watch.js:71:20)
[app-scripts]     at ontimeout (timers.js:436:11)
[app-scripts]     at tryOnTimeout (timers.js:300:5)
[app-scripts]     at listOnTimeout (timers.js:263:5)
[app-scripts]     at Timer.processTimers (timers.js:223:10)
[app-scripts] (node:916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[app-scripts] (node:916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L7:  * provide.
[app-scripts]        L9:  * Implements an iterable interface, therefore it can be used in both ES6
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L7:   * Determine if the argument is an Observable
[app-scripts]        L9:  export declare function isObservable(obj: any | Observable<any>): obj is Observable<any>;
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L7:  * Only used internally in the forms module.
[app-scripts]        L9:  * @stable
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L9:   * An interface that can be implemented by classes that can act as validators.
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L1:  import { Observable } from 'rxjs';
[app-scripts]        L2:  import { AsyncValidatorFn, ValidationErrors, ValidatorFn } from './directives/validators';
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L8:  * Provide this using `multi: true` to add validators.
[app-scripts]       L10:  * ### Example
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L1:  import { Observable } from 'rxjs';
[app-scripts]        L2:  import { ReadyState } from '../enums';
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L1:  import { Observable } from 'rxjs';
[app-scripts]        L2:  import { ResponseOptions } from '../base_response_options';
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L1:  import { Observable } from 'rxjs';
[app-scripts]        L2:  import { RequestOptions } from './base_request_options';
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L1:  import { Observable } from 'rxjs';
[app-scripts]        L2:  export interface PluginConfig {
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L1:  import { Observable } from 'rxjs';
[app-scripts]        L2:  import { CordovaOptions } from './decorators';
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L1:  import { IonicNativePlugin } from '@ionic-native/core';
[app-scripts]        L2:  import { Observable } from 'rxjs';
[app-scripts]        L3:  export interface Coordinates {
[app-scripts]             Cannot find module 'rxjs/Subscription'.
[app-scripts]        L2:  import { InjectionToken } from '@angular/core';
[app-scripts]        L3:  import { Subscription } from 'rxjs/Subscription';
[app-scripts]        L4:  export interface FirebaseAppConfig {
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L2:  import 'firebase/auth';
[app-scripts]        L3:  import { Observable } from 'rxjs/Observable';
[app-scripts]        L4:  import { FirebaseApp } from 'angularfire2';
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L2:  import 'firebase/firestore';
[app-scripts]        L3:  import { Observable } from 'rxjs/Observable';
[app-scripts]        L4:  import 'rxjs/add/operator/map';
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L2:  import 'firebase/firestore';
[app-scripts]        L3:  import { Observable } from 'rxjs/Observable';
[app-scripts]        L4:  import 'rxjs/add/operator/map';
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L2:  import 'firebase/firestore';
[app-scripts]        L3:  import { Observable } from 'rxjs/Observable';
[app-scripts]        L4:  import { QueryFn, Action } from '../interfaces';
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L2:  import 'firebase/firestore';
[app-scripts]        L3:  import { Observable } from 'rxjs/Observable';
[app-scripts]        L4:  import 'rxjs/add/operator/map';
[app-scripts]             Cannot find module 'rxjs/Subscriber'.
[app-scripts]        L1:  import { Subscriber } from 'rxjs/Subscriber';
[app-scripts]        L2:  import * as firebase from 'firebase/app';
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L1:  import * as firebase from 'firebase/app';
[app-scripts]        L2:  import { Observable } from 'rxjs/Observable';
[app-scripts]        L3:  import { Action } from '../interfaces';
[app-scripts]             Cannot find module 'rxjs/Subject'.
[app-scripts]        L2:  import { NgControl } from '@angular/forms';
[app-scripts]        L3:  import { Subject } from 'rxjs/Subject';
[app-scripts]        L4:  import 'rxjs/add/operator/takeUntil';
[app-scripts]             Cannot find module 'rxjs/Subject'.
[app-scripts]        L1:  import { AfterViewInit, ElementRef, EventEmitter, Renderer, ViewContainerRef } from '@angular/core';
[app-scripts]        L2:  import { Subject } from 'rxjs/Subject';
[app-scripts]        L3:  import 'rxjs/add/operator/takeUntil';
[app-scripts]             Cannot find module '@ionic-native/call-number/ngx'.
[app-scripts]        L8:  import { NativeGeocoder} from '@ionic-native/native-geocoder';
[app-scripts]        L9:  import {CallNumber} from '@ionic-native/call-number/ngx';
[app-scripts]       L10:  import { MyApp } from './app.component';
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L1:  import { Component } from '@angular/core';
[app-scripts]        L2:  import { Observable } from 'rxjs';
[app-scripts]        L3:  import 'rxjs/add/operator/map';
[app-scripts]             Cannot find module '@ionic-native/call-number/ngx'.
[app-scripts]       L11:  import { GalleryPage } from '../gallery/gallery';
[app-scripts]       L12:  import {CallNumber} from '@ionic-native/call-number/ngx';
[app-scripts]       L13:  //import { CallPage }      from '../call/call';
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L1:  import { YtProvider } from './../../providers/yt/yt';
[app-scripts]        L2:  import { Observable } from 'rxjs/Observable';
[app-scripts]        L3:  import { Component } from '@angular/core';
[app-scripts]             Property 'getListVideos' does not exist on type 'YtProvider'.
[app-scripts]       L17:  let listId = this.navParams.get('id');
[app-scripts]       L18:  this.videos = this.ytProvider.getListVideos(listId);
[app-scripts]       L19:  this.videos.subscribe(data =>{
[app-scripts]             Cannot find module 'rxjs/Observable'.
[app-scripts]        L3:  import { NavController, AlertController } from 'ionic-angular';
[app-scripts]        L4:  import { Observable } from 'rxjs/Observable';
[app-scripts]        L5:  @Component({
[app-scripts]             Property 'getPlaylistsForChannel' does not exist on type 'YtProvider'.
[app-scripts]       L16:  searchPlaylists() {
[app-scripts]       L17:    this.playlists = this.ytProvider.getPlaylistsForChannel(this.channelId);
[app-scripts]       L18:    this.playlists.subscribe(data => {
[app-scripts]             Cannot find module 'rxjs'.
[app-scripts]        L3:  import { Events } from 'ionic-angular';
[app-scripts]        L4:  import { Observable } from 'rxjs';
[app-scripts]        L5:  //import 'rxjs/add/operator/map';
[app-scripts] [16:26:10]  copy finished in 93.68 s
 migrated from  "rxjs": "5.5.11"

**Comment by nickofthyme** [comment]
Thanks. Yup from the looks of it you are still using the version 5 syntax. There is a huge misconception in the thread that installing `rxjs-compat` is the solution, which it's not! It removes the errors because it's adding a compatibility library to handle the breaking import changes. As soon as you upgrade `rxjs` beyond version 6, or possibly less, you must correct the syntax.

```ts
// old v5 syntax
import { Observable } from 'rxjs/Observable'
// new v6 syntax
import { Observable } from 'rxjs'
```

The solution for you is to remove all old version 5 syntax and refactoring your code to use only version 6 syntax.

See this [guide](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md#dropping-the-compatibility-layer)

It's mainly super simple, import changes and changes to the [`pipe`](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md#howto-convert-to-pipe-syntax) syntax.

Follow this guide to fix all the syntax and let me know if there are any more errors.

> PS your error log says `Cannot find module 'rxjs'` so you might need to fully reinstall your `node_modules` if you still get that error because that seems unrelated.

**Comment by riginoommen** [comment]
I really don't know why you all people are not understanding the actual issue

> > Since Angular 7, `rxjs-compat` isn't in your project automatically. Also when you run the [Angular updater](update.angular.io):
> > ![image](https://user-images.githubusercontent.com/963136/49011753-9059b300-f177-11e8-95de-eeea63483e80.png)
> 
> Hi
> 
> How to fix this while migrating from angular 5 to 7

Angular documentation itself says after migrating remove the package. I really dont think having the package in the upgraded version does n't make sense. Also for the long term also

**Comment by philly-vanilly** [comment]
Ok, it's working now. Just make sure your imports look like this then you can uninstall rxjs-compat once you are on rxjs6+:
```
import {Observable, of} from 'rxjs';
import {filter, map, mergeMap, take} from 'rxjs/operators';
```

**Comment by N-Asadnajafi** [comment]
It is working surprisingly. Thanks!

**Comment by tunggalw7** [comment]
t

**Comment by farouk2101** [comment]
Thks a lot it worked directly

**Comment by SHENAL1** [comment]
> This solved the problem on my machine
> 
> ```
> npm install --save rxjs-compat
> ```

Thanks this solved my error as well

**Comment by FrankBonilla** [comment]
Thanks so much..!!

**Comment by z3hcnas** [comment]
Gracias realmente me salvo
