### ISSUE TITLE
ng2-handsontable does not work with angular2@2.0.0-beta.13 and later

### ISSUE THREAD

**Issue by pmig** [valor-software/ng2-handsontable#69]
Hi,

This components needs some refactoring to work with the current versions of angular. Some of open tasks would be:

- [ ] import from angular2/common instead of angular2/angular2
- [ ] move from @Directive to @Component
- [ ] 'tempalte' property for @Component 
- [ ] Make sure it works with the latest HandsOnTable

**Comment by valorkin** [comment]
ok

**Comment by ivanovjaroslaw** [comment]
And it needs 'template' property for @Component.

**Comment by shadeeka** [comment]
Is there any possibility that we can use ng2-handsontable with current Angular2 RC version.
Thanks

**Comment by valorkin** [comment]
latest version of handsomtable had real mess with 3rd party dependecies
so I left an idea to update this repo for a while
