### ISSUE TITLE
Getting 2 rows of data when pasting to one row in Chrome.

### ISSUE THREAD

**Issue by nicam** [valor-software/ng2-handsontable#7]
Hi There

When you copy a row and paste it into a different row on Chrome, 2 rows are inserted instead of one.

![Gif Showing the Error](http://g.recordit.co/ibpy9VgiT2.gif)

This only seems to happen when Handsontable is running inside Angular2. I think this is somehow related to ZoneJS since this issue seems also be happening in MeteorJS when the ZoneJS Bundle is used there (https://github.com/awsp/handsontable-meteor/issues/17).

You can reproduce it here: https://valor-software.github.io/ng2-handsontable/

**Steps to reproduce:**
- Open example page in Chrome (47.0.2526.111)
- Click on a single row
- CMD+C (on Mac)
- Click on a different row (has to be writable)
- CMD+V

Two rows are inserted.

Any idea why ZoneJS might cause this issue on Chrome?

Best regards

Pascal Helfenstein

**Comment by poxrud** [comment]
Hey, not sure if you saw it but I pushed a PR to Zone.js fixing this issue.

**Comment by valorkin** [comment]
hey, that's awesome news!
this module doesn't have a dependency to zone.js
but angular2 has peer dep
did you created and issue angular2 repo about this?

**Comment by poxrud** [comment]
@valorkin I sent a PR to Handsontable which was merged into develop branch.
